package negocio.basica;
// Generated 24/09/2012 21:42:02 by Hibernate Tools 3.2.0.CR1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Chamado generated by hbm2java
 */
public class Chamado  implements java.io.Serializable {


     private int id;
     private Tipochamado tipochamado;
     private Orcamento orcamento;
     private Funcionario funcionario;
     private String nome;
     private String origem;
     private String situacao;
     private String descricao;
     private Date dtchamado;
     private String observacao;
     private Set computadors = new HashSet(0);

    public Chamado() {
    }

	
    public Chamado(int id, Tipochamado tipochamado, Orcamento orcamento, Funcionario funcionario) {
        this.id = id;
        this.tipochamado = tipochamado;
        this.orcamento = orcamento;
        this.funcionario = funcionario;
    }
    public Chamado(int id, Tipochamado tipochamado, Orcamento orcamento, Funcionario funcionario, String nome, String origem, String situacao, String descricao, Date dtchamado, String observacao, Set computadors) {
       this.id = id;
       this.tipochamado = tipochamado;
       this.orcamento = orcamento;
       this.funcionario = funcionario;
       this.nome = nome;
       this.origem = origem;
       this.situacao = situacao;
       this.descricao = descricao;
       this.dtchamado = dtchamado;
       this.observacao = observacao;
       this.computadors = computadors;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Tipochamado getTipochamado() {
        return this.tipochamado;
    }
    
    public void setTipochamado(Tipochamado tipochamado) {
        this.tipochamado = tipochamado;
    }
    public Orcamento getOrcamento() {
        return this.orcamento;
    }
    
    public void setOrcamento(Orcamento orcamento) {
        this.orcamento = orcamento;
    }
    public Funcionario getFuncionario() {
        return this.funcionario;
    }
    
    public void setFuncionario(Funcionario funcionario) {
        this.funcionario = funcionario;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getOrigem() {
        return this.origem;
    }
    
    public void setOrigem(String origem) {
        this.origem = origem;
    }
    public String getSituacao() {
        return this.situacao;
    }
    
    public void setSituacao(String situacao) {
        this.situacao = situacao;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public Date getDtchamado() {
        return this.dtchamado;
    }
    
    public void setDtchamado(Date dtchamado) {
        this.dtchamado = dtchamado;
    }
    public String getObservacao() {
        return this.observacao;
    }
    
    public void setObservacao(String observacao) {
        this.observacao = observacao;
    }
    public Set getComputadors() {
        return this.computadors;
    }
    
    public void setComputadors(Set computadors) {
        this.computadors = computadors;
    }




}


