package negocio.basica;
// Generated 24/09/2012 21:42:02 by Hibernate Tools 3.2.0.CR1


import java.util.HashSet;
import java.util.Set;

/**
 * Computador generated by hbm2java
 */
public class Computador  implements java.io.Serializable {


     private int id;
     private Chamado chamado;
     private String descricao;
     private String tipo;
     private Set softwares = new HashSet(0);
     private Set hardwares = new HashSet(0);
     private Set monitors = new HashSet(0);

    public Computador() {
    }

	
    public Computador(int id, Chamado chamado) {
        this.id = id;
        this.chamado = chamado;
    }
    public Computador(int id, Chamado chamado, String descricao, String tipo, Set softwares, Set hardwares, Set monitors) {
       this.id = id;
       this.chamado = chamado;
       this.descricao = descricao;
       this.tipo = tipo;
       this.softwares = softwares;
       this.hardwares = hardwares;
       this.monitors = monitors;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Chamado getChamado() {
        return this.chamado;
    }
    
    public void setChamado(Chamado chamado) {
        this.chamado = chamado;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public Set getSoftwares() {
        return this.softwares;
    }
    
    public void setSoftwares(Set softwares) {
        this.softwares = softwares;
    }
    public Set getHardwares() {
        return this.hardwares;
    }
    
    public void setHardwares(Set hardwares) {
        this.hardwares = hardwares;
    }
    public Set getMonitors() {
        return this.monitors;
    }
    
    public void setMonitors(Set monitors) {
        this.monitors = monitors;
    }




}


