package negocio.basica;
// Generated 24/09/2012 21:42:02 by Hibernate Tools 3.2.0.CR1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Orcamento generated by hbm2java
 */
public class Orcamento  implements java.io.Serializable {


     private int id;
     private String empresa;
     private String produto;
     private Double valor;
     private Date dtvalidade;
     private Integer qtde;
     private Set chamados = new HashSet(0);

    public Orcamento() {
    }

	
    public Orcamento(int id) {
        this.id = id;
    }
    public Orcamento(int id, String empresa, String produto, Double valor, Date dtvalidade, Integer qtde, Set chamados) {
       this.id = id;
       this.empresa = empresa;
       this.produto = produto;
       this.valor = valor;
       this.dtvalidade = dtvalidade;
       this.qtde = qtde;
       this.chamados = chamados;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(String empresa) {
        this.empresa = empresa;
    }
    public String getProduto() {
        return this.produto;
    }
    
    public void setProduto(String produto) {
        this.produto = produto;
    }
    public Double getValor() {
        return this.valor;
    }
    
    public void setValor(Double valor) {
        this.valor = valor;
    }
    public Date getDtvalidade() {
        return this.dtvalidade;
    }
    
    public void setDtvalidade(Date dtvalidade) {
        this.dtvalidade = dtvalidade;
    }
    public Integer getQtde() {
        return this.qtde;
    }
    
    public void setQtde(Integer qtde) {
        this.qtde = qtde;
    }
    public Set getChamados() {
        return this.chamados;
    }
    
    public void setChamados(Set chamados) {
        this.chamados = chamados;
    }




}


