package negocio.basica;
// Generated 24/09/2012 21:42:02 by Hibernate Tools 3.2.0.CR1


import java.util.HashSet;
import java.util.Set;

/**
 * Privilegio generated by hbm2java
 */
public class Privilegio  implements java.io.Serializable {


     private int id;
     private String nome;
     private String descricao;
     private Set funcionarios = new HashSet(0);

    public Privilegio() {
    }

	
    public Privilegio(int id) {
        this.id = id;
    }
    public Privilegio(int id, String nome, String descricao, Set funcionarios) {
       this.id = id;
       this.nome = nome;
       this.descricao = descricao;
       this.funcionarios = funcionarios;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public Set getFuncionarios() {
        return this.funcionarios;
    }
    
    public void setFuncionarios(Set funcionarios) {
        this.funcionarios = funcionarios;
    }




}


