CREATE TABLE CHAMADO (
  ID                             SERIAL NOT NULL
 ,TIPOCHAMADO_ID                 INTEGER NOT NULL
 ,ORCAMENTO_ID                   INTEGER NOT NULL
 ,FUNCIONARIO_ID                 INTEGER NOT NULL
 ,NOME                           VARCHAR(45)
 ,ORIGEM                         VARCHAR(45)
 ,SITUACAO                       VARCHAR(20)
 ,DESCRICAO                      VARCHAR(255)
 ,DTCHAMADO                      DATE
 ,OBSERVACAO                     VARCHAR(255)
 ,CONSTRAINT PK_CHAMADO PRIMARY KEY (ID)
)
;

CREATE INDEX IXFK_CHAMADO_1_FUNCIONARIO_ID ON CHAMADO (FUNCIONARIO_ID);

CREATE INDEX IXFK_CHAMADO_2_ORCAMENTO_ID ON CHAMADO (ORCAMENTO_ID);

CREATE INDEX IXFK_CHAMADO_3_TIPOCHAMADO_ID ON CHAMADO (TIPOCHAMADO_ID);

CREATE TABLE COMPUTADOR (
  ID                             SERIAL NOT NULL
 ,CHAMADO_ID                     INTEGER NOT NULL
 ,DESCRICAO                      VARCHAR(255)
 ,TIPO                           VARCHAR(20)
 ,CONSTRAINT PK_COMPUTADOR PRIMARY KEY (ID)
)
;

CREATE INDEX IXFK_COMPUTADOR_1_CHAMADO_ID ON COMPUTADOR (CHAMADO_ID);

CREATE TABLE DEPARTAMENTO (
  ID                             SERIAL NOT NULL
 ,NOME                           VARCHAR(45)
 ,DESCRICAO                      VARCHAR(255)
 ,CONSTRAINT PK_DEPARTAMENTO PRIMARY KEY (ID)
)
;

CREATE TABLE FUNCIONARIO (
  ID                             SERIAL NOT NULL
 ,DEPARTAMENTO_ID                INTEGER NOT NULL
 ,PRIVILEGIO_ID                  INTEGER NOT NULL
 ,NOME                           VARCHAR(45)
 ,EMAIL                          VARCHAR(45)
 ,CPF                            VARCHAR(20)
 ,RG                             VARCHAR(20)
 ,DTNASCIMENTO                   DATE
 ,ENDERECO                       VARCHAR(100)
 ,BAIRRO                         VARCHAR(20)
 ,CIDADE                         VARCHAR(30)
 ,CEP                            VARCHAR(9)
 ,TELEFONE                       VARCHAR(20)
 ,LOGIN                          VARCHAR(20)
 ,SENHA                          VARCHAR(20)
 ,CARGO                          VARCHAR(20)
 ,ESTADO                         VARCHAR(20)
 ,CONSTRAINT PK_FUNCIONARIO PRIMARY KEY (ID)
)
;

CREATE INDEX IXFK_FUNCIONARIO_1_PRIVILEGIO_ID ON FUNCIONARIO (PRIVILEGIO_ID);

CREATE INDEX IXFK_FUNCIONARIO_2_DEPARTAMENTO_ID ON FUNCIONARIO (DEPARTAMENTO_ID);

CREATE TABLE HARDWARE (
  ID                             SERIAL NOT NULL
 ,COMPUTADOR_ID                  INTEGER NOT NULL
 ,MARCA                          VARCHAR(45)
 ,MODELO                         VARCHAR(45)
 ,GARANTIA                       VARCHAR(45)
 ,DTCOMPRA                       DATE
 ,CONSTRAINT PK_HARDWARE PRIMARY KEY (ID)
)
;

CREATE INDEX IXFK_HARDWARE_1_COMPUTADOR_ID ON HARDWARE (COMPUTADOR_ID);

CREATE TABLE MONITOR (
  ID                             SERIAL NOT NULL
 ,COMPUTADOR_ID                  INTEGER NOT NULL
 ,MARCA                          VARCHAR(20)
 ,MODELO                         VARCHAR(20)
 ,GARANTIA                       VARCHAR(20)
 ,DTCOMPRA                       DATE
 ,TIPO                           VARCHAR(20)
 ,TAMANHO                        INTEGER
 ,CONSTRAINT PK_MONITOR PRIMARY KEY (ID)
)
;

CREATE INDEX IXFK_MONITOR_1_COMPUTADOR_ID ON MONITOR (COMPUTADOR_ID);

CREATE TABLE ORCAMENTO (
  ID                             SERIAL NOT NULL
 ,EMPRESA                        VARCHAR(20)
 ,PRODUTO                        VARCHAR(45)
 ,VALOR                          FLOAT
 ,DTVALIDADE                     DATE
 ,QTDE                           INTEGER
 ,CONSTRAINT PK_ORCAMENTO PRIMARY KEY (ID)
)
;

CREATE TABLE PRIVILEGIO (
  ID                             SERIAL NOT NULL
 ,NOME                           VARCHAR(45)
 ,DESCRICAO                      VARCHAR(255)
 ,CONSTRAINT PK_PRIVILEGIO PRIMARY KEY (ID)
)
;

CREATE TABLE SOFTWARE (
  ID                             SERIAL NOT NULL
 ,COMPUTADOR_ID                  INTEGER NOT NULL
 ,TIPO                           VARCHAR(20)
 ,NOME                           VARCHAR(45)
 ,DTCOMPRA                       DATE
 ,DTTERMINO                      DATE
 ,SERIAL                         VARCHAR(45)
 ,LIVRE                          CHAR
 ,CONSTRAINT PK_SOFTWARE PRIMARY KEY (ID)
)
;

CREATE INDEX IXFK_SOFTWARE_1_COMPUTADOR_ID ON SOFTWARE (COMPUTADOR_ID);

CREATE TABLE TIPOCHAMADO (
  ID                             SERIAL NOT NULL
 ,NOME                           VARCHAR(45)
 ,CONSTRAINT PK_TIPOCHAMADO PRIMARY KEY (ID)
)
;

ALTER TABLE CHAMADO
  ADD CONSTRAINT FK_CHAMADO_FUNCIONARIO FOREIGN KEY (FUNCIONARIO_ID)
    REFERENCES FUNCIONARIO (ID)
;
ALTER TABLE CHAMADO
  ADD CONSTRAINT FK_CHAMADO_ORCAMENTO FOREIGN KEY (ORCAMENTO_ID)
    REFERENCES ORCAMENTO (ID)
;
ALTER TABLE CHAMADO
  ADD CONSTRAINT FK_CHAMADO_TIPOCHAMADO FOREIGN KEY (TIPOCHAMADO_ID)
    REFERENCES TIPOCHAMADO (ID)
;
ALTER TABLE COMPUTADOR
  ADD CONSTRAINT FK_COMPUTADOR_CHAMADO FOREIGN KEY (CHAMADO_ID)
    REFERENCES CHAMADO (ID)
;
ALTER TABLE FUNCIONARIO
  ADD CONSTRAINT FK_FUNCIONARIO_PRIVILEGIO FOREIGN KEY (PRIVILEGIO_ID)
    REFERENCES PRIVILEGIO (ID)
;
ALTER TABLE FUNCIONARIO
  ADD CONSTRAINT FK_FUNCIONARIO_DEPARTAMENTO FOREIGN KEY (DEPARTAMENTO_ID)
    REFERENCES DEPARTAMENTO (ID)
;
ALTER TABLE HARDWARE
  ADD CONSTRAINT FK_HARDWARE_COMPUTADOR FOREIGN KEY (COMPUTADOR_ID)
    REFERENCES COMPUTADOR (ID)
;
ALTER TABLE MONITOR
  ADD CONSTRAINT FK_MONITOR_COMPUTADOR FOREIGN KEY (COMPUTADOR_ID)
    REFERENCES COMPUTADOR (ID)
;
ALTER TABLE SOFTWARE
  ADD CONSTRAINT FK_SOFTWARE_COMPUTADOR FOREIGN KEY (COMPUTADOR_ID)
    REFERENCES COMPUTADOR (ID)
;
