package negocio.basica;
// Generated 24/09/2012 21:42:02 by Hibernate Tools 3.2.0.CR1


import java.util.Date;

/**
 * Software generated by hbm2java
 */
public class Software  implements java.io.Serializable {


     private int id;
     private Computador computador;
     private String tipo;
     private String nome;
     private Date dtcompra;
     private Date dttermino;
     private String serial;
     private Character livre;

    public Software() {
    }

	
    public Software(int id, Computador computador) {
        this.id = id;
        this.computador = computador;
    }
    public Software(int id, Computador computador, String tipo, String nome, Date dtcompra, Date dttermino, String serial, Character livre) {
       this.id = id;
       this.computador = computador;
       this.tipo = tipo;
       this.nome = nome;
       this.dtcompra = dtcompra;
       this.dttermino = dttermino;
       this.serial = serial;
       this.livre = livre;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Computador getComputador() {
        return this.computador;
    }
    
    public void setComputador(Computador computador) {
        this.computador = computador;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public Date getDtcompra() {
        return this.dtcompra;
    }
    
    public void setDtcompra(Date dtcompra) {
        this.dtcompra = dtcompra;
    }
    public Date getDttermino() {
        return this.dttermino;
    }
    
    public void setDttermino(Date dttermino) {
        this.dttermino = dttermino;
    }
    public String getSerial() {
        return this.serial;
    }
    
    public void setSerial(String serial) {
        this.serial = serial;
    }
    public Character getLivre() {
        return this.livre;
    }
    
    public void setLivre(Character livre) {
        this.livre = livre;
    }




}


